'use strict';

var commands = {
  DATASERVICE_ACTIVESTORESLIST : 100,
  DATASERVICE_SPATIALQUERY : 101,
  DATASERVICE_SPATIALQUERYALL : 102,
  DATASERVICE_GEOSPATIALQUERY : 103,
  DATASERVICE_GEOSPATIALQUERYALL : 104,
  DATASERVICE_CREATEFEATURE : 105,
  DATASERVICE_UPDATEFEATURE : 106,
  DATASERVICE_DELETEFEATURE : 107,
  SENSORSERVICE_GPS : 200
};

module.exports = commands;
