'use strict';

var commands = {
  DATASERVICE_ACTIVESTORESLIST: 100,
  DATASERVICE_ACTIVESTOREBYID: 101,
  DATASERVICE_SPATIALQUERY: 110,
  DATASERVICE_SPATIALQUERYALL: 111,
  DATASERVICE_GEOSPATIALQUERY: 112,
  DATASERVICE_GEOSPATIALQUERYALL: 113,
  DATASERVICE_CREATEFEATURE: 114,
  DATASERVICE_UPDATEFEATURE: 115,
  DATASERVICE_DELETEFEATURE: 116,
  SENSORSERVICE_GPS: 200
};

module.exports = commands;
